package com.dshmobile.app.ui.theme

import androidx.compose.ui.graphics.Color

// A deliberate brand palette rather than Material You, so the app looks the same on every device
// and matches the DeepSeek Harness desktop shell. Hue anchored on DeepSeek's blue (#4D6BFE).

internal val BrandBlue = Color(0xFF4D6BFE)
internal val BrandBlueDim = Color(0xFF3A54D8)
internal val BrandBlueLight = Color(0xFFB8C5FF)

internal val LightPrimary = BrandBlue
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFE1E6FF)
internal val LightOnPrimaryContainer = Color(0xFF06165C)
internal val LightSecondary = Color(0xFF585E72)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFDDE1F9)
internal val LightOnSecondaryContainer = Color(0xFF151B2C)
internal val LightTertiary = Color(0xFF1C7A6B)
internal val LightOnTertiary = Color(0xFFFFFFFF)
internal val LightTertiaryContainer = Color(0xFFA8F2E2)
internal val LightOnTertiaryContainer = Color(0xFF00201B)
internal val LightBackground = Color(0xFFFBFAFF)
internal val LightOnBackground = Color(0xFF1A1B21)
internal val LightSurface = Color(0xFFFBFAFF)
internal val LightOnSurface = Color(0xFF1A1B21)
internal val LightSurfaceVariant = Color(0xFFE2E1EC)
internal val LightOnSurfaceVariant = Color(0xFF45464F)
internal val LightSurfaceContainer = Color(0xFFF0EFF7)
internal val LightSurfaceContainerHigh = Color(0xFFEAE9F2)
internal val LightSurfaceContainerHighest = Color(0xFFE4E3EC)
internal val LightSurfaceContainerLow = Color(0xFFF6F5FD)
internal val LightOutline = Color(0xFF767680)
internal val LightOutlineVariant = Color(0xFFC7C5D0)
internal val LightError = Color(0xFFBA1A1A)
internal val LightOnError = Color(0xFFFFFFFF)
internal val LightErrorContainer = Color(0xFFFFDAD6)
internal val LightOnErrorContainer = Color(0xFF410002)

internal val DarkPrimary = BrandBlueLight
internal val DarkOnPrimary = Color(0xFF00218C)
internal val DarkPrimaryContainer = Color(0xFF2A3F9E)
internal val DarkOnPrimaryContainer = Color(0xFFDFE3FF)
internal val DarkSecondary = Color(0xFFC1C6DD)
internal val DarkOnSecondary = Color(0xFF2A3042)
internal val DarkSecondaryContainer = Color(0xFF404659)
internal val DarkOnSecondaryContainer = Color(0xFFDDE1F9)
internal val DarkTertiary = Color(0xFF8BD6C6)
internal val DarkOnTertiary = Color(0xFF003730)
internal val DarkTertiaryContainer = Color(0xFF005046)
internal val DarkOnTertiaryContainer = Color(0xFFA8F2E2)
internal val DarkBackground = Color(0xFF111319)
internal val DarkOnBackground = Color(0xFFE3E1E9)
internal val DarkSurface = Color(0xFF111319)
internal val DarkOnSurface = Color(0xFFE3E1E9)
internal val DarkSurfaceVariant = Color(0xFF45464F)
internal val DarkOnSurfaceVariant = Color(0xFFC7C5D0)
internal val DarkSurfaceContainer = Color(0xFF1D1F27)
internal val DarkSurfaceContainerHigh = Color(0xFF272932)
internal val DarkSurfaceContainerHighest = Color(0xFF32343D)
internal val DarkSurfaceContainerLow = Color(0xFF191B22)
internal val DarkOutline = Color(0xFF90909A)
internal val DarkOutlineVariant = Color(0xFF45464F)
internal val DarkError = Color(0xFFFFB4AB)
internal val DarkOnError = Color(0xFF690005)
internal val DarkErrorContainer = Color(0xFF93000A)
internal val DarkOnErrorContainer = Color(0xFFFFDAD6)
